### ISSUE TITLE
Restore battery packs. 

### ISSUE THREAD

**Issue by correll** [correll/advancedrobotics#23]
Unfortunately, the batteries (LiPo) broke. Need to order new packs of follow instructions here http://www.electricrcaircraftguy.com/2014/10/restoring-over-discharged-LiPos.html

**Comment by correll** [comment]
The packs are actually composed of four separate sections, so we can replace just
the individual parts that actually need replacing.

http://www.hobbyking.com/hobbyking/store/__24215__Turnigy_nano_tech_5000mah_3S_65_130C_Lipo_Pack_US_Warehouse_.html

Thanks to Steve McGuire.

**Comment by ghost** [comment]
I also heard you mention that only one of the cells was damaged. So, we
could actually just buy one cell and replace it.
But before that, we could try to recover that particular cell by Low Charge
Current in NiMH charger configuration.

http://www.hobbyking.com/hobbyking/store/__18560__Turnigy_5000mAh_1S_20C_Lipoly_Single_Cell_.html

This one seems to be quite a similar cell of the 3s1p Battery, only the
constant Discharge is 20C instead of 65C

Regards,
Rohit

**Comment by correll** [comment]
I've read that repairing cells under 1V/cell is very risky as they can catch fire. I simply bought new ones.

Until then we can do anything involving the computer and sensors.

**Comment by mcguire-steve** [comment]
Investigated yesterday - the recovery at low charge current appears to have worked. Pack reassembled and ready for service.

**Comment by correll** [comment]
Awesome. I could not get it to work with the lowest settings. How do we
prevent the new packs I bought from dying?

On Fri, Sep 11, 2015 at 11:37 AM, Steve McGuire notifications@github.com
wrote:

> Closed #23 https://github.com/correll/advancedrobotics/issues/23.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/correll/advancedrobotics/issues/23#event-407326182.

## 

Assistant Professor
@correlllab, http://correll.cs.colorado.edu
Open robotics textbook: http://amzn.to/1vTjnt9 (buy), http://bit.ly/1vr7ptA
(contribute)
