### ISSUE TITLE
Jaguar battery cells unbalanced

### ISSUE THREAD

**Issue by Branden-Romero** [correll/advancedrobotics#68]
![img_20151109_153041](https://cloud.githubusercontent.com/assets/5060579/11074311/1e5b0a5c-87ac-11e5-8100-4dad0c715f97.jpg)

**Comment by Jorge-C** [comment]
Does running cell balancing not fix it?

**Comment by Branden-Romero** [comment]
It fixes it, but this is the second time after use that the battery has become unbalanced since we attached the laser scanner.

**Comment by Jorge-C** [comment]
We should recharge more often. A lot of low battery alarms for RC
airplanes/quadcopters go off at about 3.3V per cell (under load, so 3.2V
with no load is much more problematic).

Re. unbalancing by discharge, that might simply suggest that the BMS of the
jaguar is not great. Does it even have a Battery Management System?

2015-11-10 13:21 GMT-07:00 Branden Romero notifications@github.com:

**Comment by ikemole** [comment]
Just an observation...

I've noticed that the same cell seems to discharge faster than the other
five cells. Every time I was about to charge it, the lowest number always
shows on the bottom left position on LCD (as in this picture). I am
guessing that the same cell is represented in that location on the screen.

I am not sure how relevant that is.

**Comment by mcguire-steve** [comment]
The Jaguar does not have a battery management system to prevent
over-discharge or over-charging. Cell unbalancing is related to
manufacturing differences between individual cells - the fact that a single
cell is perpetually the weak link is consistent.
Long-term solution would involve a ROS node with some A/D hardware to
actively monitor battery voltage and current draw so that we can estimate
the amount of charge remaining and not damage the LiPo packs due to
over-discharge.
-Steve

**Comment by Jorge-C** [comment]
Closing as it is just an artifact of not having a BMS ( #56 ).
